#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.


# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------
# if [[ -z "$INTERFACE" ]] ; then
#     INTERFACE="${BLOCK_INSTANCE:-wlan0}"
# fi
#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.

status="$(ifconfig $BLOCK_INSTANCE | grep status | awk '{print $2}')"
address_ip="$(ifconfig $BLOCK_INSTANCE | grep inet | awk '{print $2}')"

color="#00e600"

if [[ $status = 'no' ]]; then
    color="#FFAE00"
  else
    color="#000000"
    # color="#00e600"
fi

if [ "${BLOCK_BUTTON}" -eq 3 ]; then 
  wpa_gui
fi

if [ "${BLOCK_BUTTON}" -eq 1 ]; then 
  case $BLOCK_INSTANCE in
      "wlan0")
         label=" "
         echo "<span foreground=\"$color\">$label$address_ip</span>"
         ;;
      "em0") 
         label=" "
         echo "<span foreground=\"$color\">$label$address_ip</span>"
        ;;
      "extIf") 
         label=""
         # label=" "
         IP="$(curl ifconfig.me/ip)"
         echo "<span foreground=\"$color\"> $label$IP</span>"
         exit
        ;;
    esac
fi

case $BLOCK_INSTANCE in
    "wlan0")
       label=" "
       echo "<span foreground=\"$color\">$label</span>" 
       echo "<span foreground=\"$color\">$label</span>" 
       echo "<span foreground=\"$color\">$label</span>" 
       ;;
    "em0") 
       label=" "
       echo "<span foreground=\"$color\">$label</span>" 
       echo "<span foreground=\"$color\">$label</span>" 
       echo "<span foreground=\"$color\">$label</span>" 
      ;;
    "extIf") 
       label=""
       # label=" "
       echo "<span foreground=\"$color\">$label</span>" 
       echo "<span foreground=\"$color\">$label</span>" 
       echo "<span foreground=\"$color\">$label</span>" 
      ;;
  esac


# [[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
# if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
#     echo "down"
#     echo "down"
#     echo "#FF0000"
#     exit
# fi

#------------------------------------------------------------------------

# QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
#
# #------------------------------------------------------------------------
# echo $QUALITY% # full text
# echo $QUALITY% # short text
#
# # color
# if [[ $QUALITY -ge 80 ]]; then
#     echo "#00FF00"
# elif [[ $QUALITY -ge 60 ]]; then
#     echo "#FFF600"
# elif [[ $QUALITY -ge 40 ]]; then
#     echo "#FFAE00"
# else
#     echo "#FF0000"
# fi
